import type { Post, Pillar } from './types'

export const DUMMY_POSTS: Post[] = [
  {
    id: 'post1',
    accountHandle: '@honda.arta',
    profileImageSrc: '/images/profile_honda.arta.jpg',
    date: 'May 18, 2026',
    postImageSrc: '/images/post1.jpg',
    likesCount: 154,
    commentsCount: 0,
    caption: 'Waktunya ciptakan petualangan baru bersama keluarga! Dengan Honda BRV setiap perjalanan menjadi lebih seru, aman, dan nyaman. #HondaArta #HondaBRV #MobilKeluarga',
    category: 'Product Info',
    format: 'Carousel',
    instagramUrl: 'https://www.instagram.com/p/DXqFkj9ic69/',
  },
  {
    id: 'post2',
    accountHandle: '@hondaimora',
    profileImageSrc: '/images/profile_hondaimora.jpg',
    date: 'May 20, 2026',
    postImageSrc: '/images/post2.jpg',
    likesCount: 138,
    commentsCount: 3,
    caption: 'Selamat kepada pemenang undian Honda Brio dari Dealer Honda Jakarta Center periode Maret 2026. Terima kasih atas kepercayaannya kepada kami. #HondaImora #HondaJakartaCenter',
    category: 'Promo',
    format: 'Reels',
    instagramUrl: 'https://www.instagram.com/p/DXssYr0kXY5/',
  },
  {
    id: 'post3',
    accountHandle: '@honda.arta',
    profileImageSrc: '/images/profile_honda.arta.jpg',
    date: 'May 21, 2026',
    postImageSrc: '/images/post3.jpg',
    likesCount: 126,
    commentsCount: 0,
    caption: 'Siapa bilang gaya tidak bisa sejalan dengan tanggung jawab? Honda HR-V e:HEV membuktikan bahwa Anda bisa tampil elegan sekaligus peduli lingkungan. #HondaArta #HondaHRVeHEV',
    category: 'Product Info',
    format: 'Static Post',
    instagramUrl: 'https://www.instagram.com/p/DXvsNJJCahz/',
  },
  {
    id: 'post4',
    accountHandle: '@hondaimora',
    profileImageSrc: '/images/profile_hondaimora.jpg',
    date: 'May 22, 2026',
    postImageSrc: '/images/post4.jpg',
    likesCount: 107,
    commentsCount: 3,
    caption: 'Ini dia salah satu tips merawat transmisi mobil, supaya tetap awet setelah digunakan!! Dan jangan lupa service mobil Honda kalian di bengkel resmi dealer Honda Jakarta Center! #ServiceMobilHonda',
    category: 'Product Info',
    format: 'Reels',
    instagramUrl: 'https://www.instagram.com/p/DXvzqHBx0nC/',
  },
  {
    id: 'post5',
    accountHandle: '@hondaimora',
    profileImageSrc: '/images/profile_hondaimora.jpg',
    date: 'May 19, 2026',
    postImageSrc: '/images/post5.jpg',
    likesCount: 91,
    commentsCount: 2,
    caption: 'Rasakan sensasi berkendara yang beda bareng Honda WR-V! SUV compact yang nggak cuma stylish, tapi juga siap nemenin setiap perjalanan kamu. Dilengkapi Honda SENSING & ground clearance tinggi. #HondaWRV',
    category: 'Product Info',
    format: 'Static Post',
    instagramUrl: 'https://www.instagram.com/p/DXqTqJsCTFz/',
  },
  {
    id: 'post6',
    accountHandle: '@honda.arta',
    profileImageSrc: '/images/profile_honda.arta.jpg',
    date: 'May 20, 2026',
    postImageSrc: '/images/post6.jpg',
    likesCount: 91,
    commentsCount: 0,
    caption: 'Semangat Kebangkitan Nasional terus kita jaga — untuk setiap langkah yang terus bergerak maju bersama. Selamat Hari Kebangkitan Nasional 2026. #HarKitnas2026 #HondaArta',
    category: 'Credibility',
    format: 'Static Post',
    instagramUrl: 'https://www.instagram.com/p/DXx_fjkCS_g/',
  },
  {
    id: 'post7',
    accountHandle: '@hondaimora',
    profileImageSrc: '/images/profile_hondaimora.jpg',
    date: 'May 23, 2026',
    postImageSrc: '/images/post7.jpg',
    likesCount: 91,
    commentsCount: 2,
    caption: 'Final hasil uji efisiensi bahan bakar Honda HR-V Hybrid 2026. Gimana menurut kalian?? Test drive dulu seberapa nyaman dan aman mobil Honda HR-V Hybrid 2026. #HondaHRVHybrid #HondaImora',
    category: 'Product Info',
    format: 'Reels',
    instagramUrl: 'https://www.instagram.com/p/DXvbAY8xln-/',
  },
  {
    id: 'post8',
    accountHandle: '@hondaimora',
    profileImageSrc: '/images/profile_hondaimora.jpg',
    date: 'May 19, 2026',
    postImageSrc: '/images/post8.jpg',
    likesCount: 69,
    commentsCount: 1,
    caption: 'Sehubung dengan memperingati Hari Kebangkitan Nasional, 20 Mei 2026, Pelayanan Service dan Sales Dealer Honda Jakarta Center tutup sementara dan beroperasi kembali Rabu, 21 Mei 2026. #HondaImora',
    category: 'Credibility',
    format: 'Static Post',
    instagramUrl: 'https://www.instagram.com/p/DXvTO3yCbxX/',
  },
  {
    id: 'post9',
    accountHandle: '@hondaimora',
    profileImageSrc: '/images/profile_hondaimora.jpg',
    date: 'May 25, 2026',
    postImageSrc: '/images/post9.jpg',
    likesCount: 65,
    commentsCount: 3,
    caption: 'Selamat kepada pemenang Quiz Honda Imora periode 18 Mei 2026 — @hadi_ruwadi & @nirrin16. Segera kirimkan data diri ke DM. Tunggu Quiz Honda Imora selanjutnya! #HondaImora #QuizHondaImora',
    category: 'Promo',
    format: 'Carousel',
    instagramUrl: 'https://www.instagram.com/p/DXvfWneieRa/',
  },
  {
    id: 'post10',
    accountHandle: '@hondaimora',
    profileImageSrc: '/images/profile_hondaimora.jpg',
    date: 'May 20, 2026',
    postImageSrc: '/images/post10.jpg',
    likesCount: 59,
    commentsCount: 1,
    caption: 'Selamat Hari Kebangkitan Nasional 2026! 20 Mei menjadi pengingat semangat bangkit bersama — tentang menghargai setiap usaha dan dedikasi untuk Indonesia. Bangkit, maju, bersama! #HarKitnas2026 #HondaImora',
    category: 'Credibility',
    format: 'Static Post',
    instagramUrl: 'https://www.instagram.com/p/DXxt3Mikq12/',
  },
]

export const DUMMY_PILLARS: Pillar[] = [
  {
    number: 1,
    label: 'Pillar 01',
    title: 'Product Value & Information',
    postCount: 5,
    ideas: [
      {
        title: 'Honda HR-V eHEV: Gaya Sekaligus Ramah Lingkungan',
        description: 'Film sales advisor kamu menjelaskan satu perbedaan nyata antara HR-V eHEV dan HR-V biasa saat customer test drive — fokus pada momen "wah" pertama kali merasakan torsi listrik. Format: 20 detik, shot dari dalam kabin, CTA "Mau coba sendiri? DM kami."',
        format: 'Reels',
      },
      {
        title: 'Tips Perawatan Mobil Honda',
        description: 'Minta mekanik senior showroommu tunjukkan satu kesalahan paling sering terjadi saat pemilik Honda servis sendiri — misalnya interval ganti oli yang salah untuk CVT. Format: 15 detik, close-up tangan mekanik, text overlay tips, CTA booking servis.',
        format: 'Reels',
      },
      {
        title: 'Honda WR-V: SUV untuk Semua Petualangan',
        description: 'Buat carousel 5 slide dengan foto unit WR-V di showroommu — tiap slide highlight satu fitur spesifik (SENSING, ground clearance, kapasitas bagasi). Gunakan angka dari brosur resmi Honda sebagai referensi. Sales advisormu jadi narator di caption. Slide terakhir: harga OTR + CTA test drive.',
        format: 'Carousel',
      },
    ],
  },
  {
    number: 2,
    label: 'Pillar 02',
    title: 'Dealer Credibility',
    postCount: 3,
    ideas: [
      {
        title: 'Sales Advisor Honda: Lebih dari Sekadar Jual Mobil',
        description: 'Rekam sales advisormu saat mendampingi customer test drive pertama — tunjukkan cara mereka menjelaskan fitur mobil, bukan sekadar membaca spesifikasi. Format: 20–30 detik candid, suasana showroom asli di background, tutup dengan CTA "Booking test drive gratis via DM."',
        format: 'Reels',
      },
      {
        title: 'Momen Hari Nasional Dealer',
        description: 'Design static post Hari Kebangkitan Nasional (20 Mei) pakai foto tim dealermu sendiri — bukan stok foto Honda. Caption 1 kalimat yang hubungkan tema "bangkit" ke program cicilan atau layanan servis terbaru. Posting H-1 pagi untuk dapat early engagement.',
        format: 'Static Post',
      },
      {
        title: 'Kenalan dengan Tim Honda Kami',
        description: 'Spotlight satu anggota tim dealermu minggu ini — sales advisor, mekanik, atau kepala bengkel. Foto + caption 3 poin: nama & jabatan, sudah berapa tahun di Honda, rekomendasi model Honda untuk keluarga muda. Jadikan seri mingguan yang konsisten.',
        format: 'Static Post',
      },
    ],
  },
  {
    number: 3,
    label: 'Pillar 03',
    title: 'Customer Story',
    postCount: 0,
    postCountNote: 'peluang terbuka',
    ideas: [
      {
        title: 'Cerita Honda Lover Kamu',
        description: 'Tanya customer yang baru ambil CR-V atau WR-V: "Kenapa pilih Honda bukan kompetitor?" — rekam jawaban jujur mereka 15–30 detik, tanpa script. Munculkan nama dan kota mereka di text overlay. Reaksi yang autentik lebih menjual dari video produksi mahal.',
        format: 'Reels',
      },
      {
        title: 'Delivery Day Moments',
        description: 'Setiap serah terima kunci, foto customer (dengan izin) sambil pegang kunci di depan unit barunya di showroom. Caption: nama + model + kota + 1 kalimat kenapa mereka pilih Honda. Tag customer untuk UGC organik. Jadikan seri mingguan yang konsisten.',
        format: 'Static Post',
      },
      {
        title: 'Testimoni Servis Berkala',
        description: 'Saat customer selesai servis berkala, minta 30 detik: "Sudah berapa kali servis di sini? Apa yang bikin kamu balik lagi?" — rekam di area servis dengan suasana showroom asli di background. Jangan overedit. Autentisitas lebih bernilai dari produksi mahal.',
        format: 'Reels',
      },
    ],
  },
  {
    number: 4,
    label: 'Pillar 04',
    title: 'Promo Activation / Activities',
    postCount: 2,
    ideas: [
      {
        title: 'Pengumuman Pemenang Undian',
        description: 'Rekam momen live saat nama pemenang undian dipanggil di showroom — reaksi kejutan dan bahagia adalah kontennya. Tambah countdown "siapa pemenang berikutnya?" di akhir untuk drive antisipasi promo bulan depan. Format: 30 detik, shot wajah pemenang, tidak perlu produksi mahal.',
        format: 'Reels',
      },
      {
        title: 'Quiz + Merchandise Dealer',
        description: 'Carousel 3 slide: (1) foto merchandise + pertanyaan trivia spesifik ("Berapa ground clearance WR-V?"), (2) hint dengan foto fitur unit, (3) cara ikut + deadline. Jawaban di kolom komentar, wajib tag 1 teman. Desain pakai warna merah Honda — bukan flat template generik.',
        format: 'Carousel',
      },
      {
        title: 'Event Tie-in Giveaway',
        description: 'Untuk Idul Adha, minta followers kirim foto momen Idul Adha mereka bersama Honda di komentar atau DM. Sales advisormu announce di video 15 detik — tunjukkan hadiah fisik (merchandise atau voucher servis). Umumkan 1 pemenang di H+2 Idul Adha.',
        format: 'Reels',
      },
    ],
  },
]

export const ACCOUNTS = [
  '@hondaimora',
  '@honda.cibubur',
  '@hondapermatahijauofficial',
  '@hondamegatamakalimalang',
  '@hondamegatamakapuk',
  '@hondapasarminggu',
  '@honda.arta',
  '@hondabintangcimone',
]
